name : Deploy messagingService to vps

on:
    push: 
        branches: 
            -main

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

            - name: Deploy backend and fix permissions
              run: |
                    ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
                        cd /var/www/axeiro/messagingService
                        git pull origin master
                        npm install

                        # Restart backend via PM2
                        pm2 restart axeiro || pm2 start messagingService.js --name axeiro
                        pm2 save

                        # Fix ownership and permissions (automated)
                        sudo chown -R www-data:www-data /var/www/axeiro/messagingService
                        sudo chmod -R 755 /var/www/axeiro/messagingService
                    EOF